"""followers

Revision ID: 769f19a3b504
Revises: f8c72bc42da8
Create Date: 2021-01-14 20:52:28.630985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769f19a3b504'
down_revision = 'f8c72bc42da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
